[DefaultPaths]
data_folder = 2-data
output_folder = 1-output

[DataSource]
source_api = yfinance

[Visualization]
# Bloomberg orange: #FF9900
style = dark_background
main_color = #FF9900
font_color = #FFFFFF
grid_color = #444444
font_size = 12
figure_width = 15
figure_height = 7